# Generated by Django 3.1.2 on 2020-12-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
